.nh
.TH "true-knowledge" "1" "Sep 2026" "true-knowledge" "tk (true-knowledge)"

.SH NAME
tk-config-get - Get one setting


.SH SYNOPSIS
\fBtk config get  [flags]\fP


.SH DESCRIPTION
Get one setting


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for get


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--budget\fP=0
	char budget override (0 = config defaults)

.PP
\fB--home\fP=""
	override base home (TK_HOME equivalent: config+data+cache+state under it)

.PP
\fB--json\fP[=false]
	stable JSON envelope output


.SH SEE ALSO
\fBtk-config(1)\fP
