.nh
.TH "true-knowledge" "1" "Sep 2026" "true-knowledge" "tk (true-knowledge)"

.SH NAME
tk-init - Create true-knowledge dirs + default config


.SH SYNOPSIS
\fBtk init [flags]\fP


.SH DESCRIPTION
Create true-knowledge dirs + default config


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for init


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--budget\fP=0
	char budget override (0 = config defaults)

.PP
\fB--home\fP=""
	override base home (TK_HOME equivalent: config+data+cache+state under it)

.PP
\fB--json\fP[=false]
	stable JSON envelope output


.SH EXAMPLE
.EX
  tk init
  TK_HOME=/tmp/x tk init
.EE


.SH SEE ALSO
\fBtk(1)\fP
