.nh
.TH "true-knowledge" "1" "Sep 2026" "true-knowledge" "tk (true-knowledge)"

.SH NAME
tk-ledger-update - Replace a project ledger (truncated to budgets.ledger_chars)


.SH SYNOPSIS
\fBtk ledger update   [flags]\fP


.SH DESCRIPTION
Replace a project ledger (truncated to budgets.ledger_chars)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for update


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--budget\fP=0
	char budget override (0 = config defaults)

.PP
\fB--home\fP=""
	override base home (TK_HOME equivalent: config+data+cache+state under it)

.PP
\fB--json\fP[=false]
	stable JSON envelope output


.SH EXAMPLE
.EX
  tk ledger update demo "demo serves the public API; deploys weekly; owned by platform."
.EE


.SH SEE ALSO
\fBtk-ledger(1)\fP
