.nh
.TH "true-knowledge" "1" "Sep 2026" "true-knowledge" "tk (true-knowledge)"

.SH NAME
tk-ledger-update - Append one immutable ledger entry (key=goal|next|done|decisions|open_questions)


.SH SYNOPSIS
\fBtk ledger update    [flags]\fP


.SH DESCRIPTION
Append one immutable ledger entry (key=goal|next|done|decisions|open_questions)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for update


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--budget\fP=0
	char budget override (0 = config defaults)

.PP
\fB--home\fP=""
	override base home (TK_HOME equivalent: config+data+cache+state under it)

.PP
\fB--json\fP[=false]
	stable JSON envelope output


.SH EXAMPLE
.EX
  tk ledger update demo goal "build a codebase-cognizant agent"
  tk ledger update demo done "shipped picker + man pages"
.EE


.SH SEE ALSO
\fBtk-ledger(1)\fP
