.nh
.TH "true-knowledge" "1" "Sep 2026" "true-knowledge" "tk (true-knowledge)"

.SH NAME
tk-migrate - Move legacy ~/.tk / $TK_HOME / Library tree into XDG true-knowledge dirs


.SH SYNOPSIS
\fBtk migrate [flags]\fP


.SH DESCRIPTION
Move legacy ~/.tk / $TK_HOME / Library tree into XDG true-knowledge dirs


.SH OPTIONS
\fB--dry-run\fP[=false]
	print without writing

.PP
\fB--force\fP[=false]
	overwrite an existing config.json / tk.json

.PP
\fB--from\fP=""
	legacy dir (default: auto-detect ~/.tk, $TK_HOME, Library)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for migrate


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--budget\fP=0
	char budget override (0 = config defaults)

.PP
\fB--home\fP=""
	override base home (TK_HOME equivalent: config+data+cache+state under it)

.PP
\fB--json\fP[=false]
	stable JSON envelope output

.PP
\fB--quiet\fP[=false]
	stderr carries errors only; suppress progress (TK_LOG=error)

.PP
\fB--verbose\fP[=false]
	debug narration on stderr (TK_LOG=debug)


.SH EXAMPLE
.EX
  tk migrate --dry-run
  tk migrate --from ~/.tk
  tk migrate --force
.EE


.SH SEE ALSO
\fBtk(1)\fP
