.nh
.TH "true-knowledge" "1" "Sep 2026" "true-knowledge" "tk (true-knowledge)"

.SH NAME
tk-mem-review - Approve/reject captured facts (never stored until approved)


.SH SYNOPSIS
\fBtk mem review [flags]\fP


.SH DESCRIPTION
Approve/reject captured facts (never stored until approved)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for review


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--budget\fP=0
	char budget override (0 = config defaults)

.PP
\fB--home\fP=""
	override base home (TK_HOME equivalent: config+data+cache+state under it)

.PP
\fB--json\fP[=false]
	stable JSON envelope output


.SH SEE ALSO
\fBtk-mem(1)\fP, \fBtk-mem-review-approve(1)\fP, \fBtk-mem-review-list(1)\fP, \fBtk-mem-review-reject(1)\fP
