.nh
.TH "true-knowledge" "1" "Sep 2026" "true-knowledge" "tk (true-knowledge)"

.SH NAME
tk-outline - Declarations in one file, in source order (cheap read alternative)


.SH SYNOPSIS
\fBtk outline  [project] [flags]\fP


.SH DESCRIPTION
Declarations in one file, in source order (cheap read alternative)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for outline

.PP
\fB--label\fP=""
	comma-separated node-label filter

.PP
\fB--limit\fP=100
	max declarations

.PP
\fB--project\fP=""
	project name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--budget\fP=0
	char budget override (0 = config defaults)

.PP
\fB--home\fP=""
	override base home (TK_HOME equivalent: config+data+cache+state under it)

.PP
\fB--json\fP[=false]
	stable JSON envelope output


.SH EXAMPLE
.EX
  tk outline orders.go demo
  tk outline src/main.go --label Function
.EE


.SH SEE ALSO
\fBtk(1)\fP
